apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: spiceroute
data:
  SERVICE_NAME: "auth-service"
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  MONGODB_HOST: "mongodb.spiceroute.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "spiceroute"
  ELASTICSEARCH_HOST: "elasticsearch.spiceroute.svc.cluster.local"
  ELASTICSEARCH_PORT: "9200" 