apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: spiceroute
type: Opaque
stringData:
  JWT_SECRET_KEY: "your-secret-key-here"  # Change in production
  MONGODB_URL: "mongodb://mongodb.spiceroute.svc.cluster.local:27017/spiceroute"
  ELASTICSEARCH_URL: "http://elasticsearch.spiceroute.svc.cluster.local:9200"
  GOOGLE_CLIENT_ID: "your-google-client-id"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret"
  FACEBOOK_CLIENT_ID: "your-facebook-app-id"
  FACEBOOK_CLIENT_SECRET: "your-facebook-app-secret" 