apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: spiceroute
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: auth-service 