apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: spiceroute
spec:
  selector:
    app: consumer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP 