apiVersion: v1
kind: Service
metadata:
  name: store-service
  namespace: spiceroute
spec:
  selector:
    app: store-service
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 