apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"elasticsearch","namespace":"spiceroute"},"spec":{"ports":[{"name":"http","port":9200,"targetPort":9200},{"name":"transport","port":9300,"targetPort":9300}],"selector":{"app":"elasticsearch"},"type":"ClusterIP"}}
  creationTimestamp: "2025-04-07T04:54:53Z"
  name: elasticsearch
  namespace: spiceroute
  resourceVersion: "1609"
  uid: f80fe279-02d3-4549-bb80-0bec749766da
spec:
  clusterIP: 10.107.202.49
  clusterIPs:
  - 10.107.202.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
