apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: spiceroute
data:
  kong.yml: |
    _format_version: "3.0"
    services:
    - name: auth-service
      url: http://auth-service.spiceroute.svc.cluster.local:8000
      routes:
      - name: auth-routes
        paths:
        - /auth
        - /auth/
        - /auth/.*
        methods:
        - POST
        - GET
        strip_path: true
    - name: store-service
      url: http://store-service.spiceroute.svc.cluster.local:8000
      routes:
      - name: store-routes
        paths:
        - /store
        - /store/
        - /store/.*
        methods:
        - GET
        - POST
        - PUT
        - DELETE
        strip_path: true
        plugins:
        - name: jwt
          config:
            header_names: ["Authorization"]
            claims_to_verify:
              exp: true
        - name: rate-limiting
          config:
            minute: 60
            policy: local
    - name: catalog-service
      url: http://catalog-service.spiceroute.svc.cluster.local:8000
      routes:
      - name: catalog-public-routes
        paths:
        - /catalog/items$
        - /catalog/items/[^/]+$
        - /catalog/search
        - /catalog/featured
        - /catalog/stores/[^/]+/items$
        methods:
        - GET
        strip_path: true
        plugins:
        - name: rate-limiting
          config:
            minute: 60
            policy: local
      - name: catalog-protected-routes
        paths:
        - /catalog/items$
        - /catalog/items/
        - /catalog/items/.*
        methods:
        - POST
        - PUT
        - DELETE
        strip_path: true
        plugins:
        - name: jwt
          config:
            header_names: ["Authorization"]
            claims_to_verify:
              exp: true
        - name: rate-limiting
          config:
            minute: 60
            policy: local 