apiVersion: v1
kind: Service
metadata:
  name: spiceroute-api
  namespace: spiceroute
  labels:
    app: spiceroute
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: spiceroute
    tier: backend 